/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateRegisterCard: typeof import('./components/cards/CreateRegisterCard.vue')['default']
    DashboardNav: typeof import('./components/dashboard-nav/DashboardNav.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RegisterCard: typeof import('./components/cards/RegisterCard.vue')['default']
    RegisterDataTable: typeof import('./components/cards/RegisterDataTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
